export const CATALOG_SOURCE_SETTING_KEY = "program-catalog-source";
export const CATALOG_AUTO_SYNC_SETTING_KEY = "program-catalog-auto-sync-v1";

// Public read-only catalogue supplied for the shared Kamiunity programme list.
// Keep the starter catalogue as the offline fallback when this feed is unavailable.
export const SHARED_CATALOG_SOURCE = {
  label: "Kamiunity program database",
  inputUrl: "https://docs.google.com/spreadsheets/d/1vu_kdUPWucy6F7lUvieuTA5MHct18aj-eha8FYTDK_s/edit?gid=48979760#gid=48979760",
};

export const DEFAULT_CATALOG_SOURCE = {
  mode: "starter",
  label: "Kamiunity starter catalog",
  inputUrl: "",
  url: "",
  rowCount: 8,
  skippedRows: 0,
  lastSyncedAt: null,
};

// These are intentionally starter records, not a current admissions feed.
// Students should verify deadlines, fees, and requirements against the official source.
export const STARTER_CATALOG = [
  {
    catalogId: "starter-utoronto-msc-computer-science",
    name: "University of Toronto",
    program: "MSc Computer Science",
    country: "Canada",
    city: "Toronto",
    department: "Computer Science",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "2 years",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://www.utoronto.ca/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
  {
    catalogId: "starter-tum-msc-informatics",
    name: "TU Munich",
    program: "MSc Informatics",
    country: "Germany",
    city: "Munich",
    department: "Computer Science",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "2 years",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://www.tum.de/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
  {
    catalogId: "starter-kuleuven-msc-data-science",
    name: "KU Leuven",
    program: "MSc Data Science",
    country: "Belgium",
    city: "Leuven",
    department: "Computer Science",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "2 years",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://www.kuleuven.be/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
  {
    catalogId: "starter-uva-msc-artificial-intelligence",
    name: "University of Amsterdam",
    program: "MSc Artificial Intelligence",
    country: "Netherlands",
    city: "Amsterdam",
    department: "Informatics Institute",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "2 years",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://www.uva.nl/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
  {
    catalogId: "starter-edinburgh-msc-ai",
    name: "University of Edinburgh",
    program: "MSc Artificial Intelligence",
    country: "United Kingdom",
    city: "Edinburgh",
    department: "School of Informatics",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "1 year",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://www.ed.ac.uk/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
  {
    catalogId: "starter-ubc-msc-computer-science",
    name: "University of British Columbia",
    program: "MSc Computer Science",
    country: "Canada",
    city: "Vancouver",
    department: "Computer Science",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "2 years",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://www.ubc.ca/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
  {
    catalogId: "starter-eth-msc-data-science",
    name: "ETH Zurich",
    program: "MSc Data Science",
    country: "Switzerland",
    city: "Zurich",
    department: "Computer Science",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "2 years",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://ethz.ch/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
  {
    catalogId: "starter-helsinki-msc-computer-science",
    name: "University of Helsinki",
    program: "MSc Computer Science",
    country: "Finland",
    city: "Helsinki",
    department: "Computer Science",
    degreeLevel: "Master’s",
    intake: "Fall 2027",
    duration: "2 years",
    language: "English",
    studyMode: "On campus",
    deadline: "",
    deadlineNote: "Verify the current cycle on the official program page.",
    priority: "Medium",
    url: "https://www.helsinki.fi/",
    portalUrl: "",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "",
    fundingUrl: "",
    requirements: "",
    languageRequirements: "",
    minimumGpa: "",
    professors: [],
    notes: "Starter record — verify before using.",
    catalogSource: "Starter catalog",
    catalogSourceUrl: "",
    catalogLastVerified: "Example record — verify",
  },
];
