export const POLIMI_CATALOGUE_URL =
  "https://www.polimi.it/en/education/laurea-magistrale-programmes";

const POLIMI_PROGRAM_URL_BASE =
  "https://www.polimi.it/en/education/laurea-magistrale-programmes/programme-detail/";

const POLIMI_PROGRAM_DEFINITIONS = [
  ["Aeronautical Engineering", "Engineering", "Milan", "English", "aeronautical-engineering"],
  ["Agricultural Engineering", "Engineering", "Cremona", "English", "agricultural-engineering"],
  ["Architectural Design and History", "Architecture & Urbanism", "Mantua", "English", "architectural-design-and-history"],
  ["Architectural Engineering", "Architecture & Urbanism", "Lecco", "English", "architectural-engineering"],
  ["Architecture", "Architecture & Urbanism", "Milan", "Italian / English", "architecture"],
  ["Automation and Control Engineering", "Engineering", "Milan", "English", "automation-and-control-engineering"],
  ["Bioinformatics for Computational Genomics", "Computer Science & Data", "Milan", "English", "bioinformatics-for-computational-genomics"],
  ["Biomedical Engineering", "Health & Biomedical", "Milan", "Italian / English", "biomedical-engineering-1"],
  ["Building Engineering for Sustainability", "Architecture & Urbanism", "Milan", "Italian / English", "building-engineering-for-sustainability"],
  ["Chemical Engineering", "Engineering", "Milan", "English", "chemical-engineering"],
  ["Civil Engineering", "Engineering", "Milan", "Italian / English", "civil-engineering"],
  ["Civil Engineering for Risk Mitigation", "Engineering", "Lecco", "English", "civil-engineering-for-risk-mitigation"],
  ["Communication Design", "Design & Creative Arts", "Milan", "Italian / English", "communication-design"],
  ["Computer Science and Engineering", "Computer Science & Data", "Milan", "English", "computer-science-and-engineering"],
  ["Cyber Risk Strategy and Governance", "Computer Science & Data", "Partner university", "English", "cyber-risk-strategy-and-governance"],
  ["Design & Engineering", "Design & Creative Arts", "Milan", "English", "design-engineering"],
  ["Design for the Fashion System", "Design & Creative Arts", "Milan", "English", "design-for-the-fashion-system"],
  ["Digital and Interaction Design", "Design & Creative Arts", "Milan", "English", "digital-and-interaction-design"],
  ["Electrical Engineering", "Engineering", "Milan", "English", "electrical-engineering"],
  ["Electronics Engineering", "Engineering", "Milan", "English", "electronics-engineering"],
  ["Energy Engineering", "Engineering", "Piacenza / Milan", "English", "energy-engineering"],
  ["Engineering Physics", "Science & Mathematics", "Milan", "English", "engineering-physics"],
  ["Environmental and Land Planning Engineering", "Sustainability & Environment", "Milan", "Italian / English", "environmental-and-land-planning-engineering"],
  ["Food Engineering", "Engineering", "Milan", "English", "food-engineering"],
  ["Geoinformatics Engineering", "Engineering", "Milan", "English", "geoinformatics-engineering"],
  ["Health Informatics", "Health & Biomedical", "Partner university", "English", "health-informatics"],
  ["High Performance Computing Engineering", "Computer Science & Data", "Milan", "English", "high-performance-computing-engineering"],
  ["Industrial Safety and Risk Engineering", "Engineering", "Milan", "English", "industrial-safety-and-risk-engineering"],
  ["Integrated Product Design", "Design & Creative Arts", "Milan", "Italian / English", "integrated-product-design"],
  ["Interior and Spatial Design", "Design & Creative Arts", "Milan", "Italian / English", "interior-and-spatial-design"],
  ["Landscape Architecture - Land Landscape Heritage", "Architecture & Urbanism", "Piacenza", "English", "landscape-architecture-land-landscape-heritage"],
  ["Management Engineering", "Business & Management", "Milan", "English", "management-engineering"],
  ["Management of Built Environment", "Architecture & Urbanism", "Milan", "English", "management-of-built-environment"],
  ["Materials Engineering and Nanotechnology", "Engineering", "Milan", "English", "materials-engineering-and-nanotechnology"],
  ["Mathematical Engineering", "Science & Mathematics", "Milan", "English", "mathematical-engineering"],
  ["Mechanical Engineering", "Engineering", "Lecco / Piacenza / Milan", "English", "mechanical-engineering"],
  ["Mobility Engineering", "Engineering", "Milan", "English", "mobility-engineering"],
  ["Music and Acoustic Engineering", "Science & Mathematics", "Milan / Cremona", "English", "music-and-acoustic-engineering"],
  ["Nuclear Engineering", "Engineering", "Milan", "English", "nuclear-engineering"],
  ["Product Service System Design", "Design & Creative Arts", "Milan", "English", "product-service-system-design"],
  ["Space Engineering", "Engineering", "Milan", "English", "space-engineering"],
  ["Sustainable Architecture and Landscape Design", "Architecture & Urbanism", "Piacenza", "English", "sustainable-architecture-and-landscape-design"],
  ["Telecommunication Engineering", "Engineering", "Milan", "English", "telecommunication-engineering"],
  ["Transformative Sustainability", "Sustainability & Environment", "Milan", "English", "transformative-sustainability"],
  ["Urban Planning and Policy Design", "Architecture & Urbanism", "Milan", "English", "urban-planning-and-policy-design"],
];

export const POLIMI_CATALOG = POLIMI_PROGRAM_DEFINITIONS.map(
  ([program, category, city, language, slug]) => ({
    catalogId: `polimi-msc-${slug}`,
    name: "Politecnico di Milano",
    program,
    country: "Italy",
    city,
    department: category,
    category,
    degreeLevel: "Master’s",
    intake: "Fall",
    duration: "2 years",
    language,
    studyMode: "On campus",
    qsRanking: "87",
    deadline: "",
    deadlineNote: "Verify the current admission call and programme-specific deadline on the official Polimi page.",
    priority: "Medium",
    url: `${POLIMI_PROGRAM_URL_BASE}${slug}`,
    portalUrl: "https://www.polimi.it/en/prospective-students",
    admissionsEmail: "",
    tuition: "",
    applicationFee: "",
    funding: "Merit scholarships and tuition support may be available; verify the current call.",
    fundingUrl: "https://www.polimi.it/en/prospective-students/tuition-fees-scholarships-and-financial-aid",
    requirements: "Relevant bachelor’s degree or equivalent; verify programme-specific entry requirements.",
    languageRequirements: "Verify the current English or Italian language proof required for the programme.",
    minimumGpa: "",
    professors: [],
    notes: "Official Politecnico di Milano Master of Science programme. Verify admission dates, fees, language, and requirements before applying.",
    catalogSource: "Politecnico di Milano official catalogue",
    catalogSourceUrl: POLIMI_CATALOGUE_URL,
    catalogLastVerified: "2026-09-06",
  }),
);
